### ISSUE TITLE
Fails to build to `wasm32-unknown-unknown` target

### ISSUE THREAD

**Issue by zylkowski** [nagisa/rust_libloading#91] opened 2021-05-11 16:37 UTC
I'm trying to build to `wasm32-unknown-unknown` target but I get several errors that `imp` is not declared
```
error[E0433]: failed to resolve: use of undeclared crate or module `imp`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libloading-0.7.0/src/lib.rs:63:20
   |
63 | pub struct Library(imp::Library);
   |                    ^^^ use of undeclared crate or module `imp`
```

**Comment by nagisa** [comment] 2021-05-11 16:38
Largely a duplicate of https://github.com/nagisa/rust_libloading/issues/23, probably. I don't really know much about wasm so it would be really helpful if somebody contributed a reasonable design/semantics/implementation here.

**Comment by Cyborus04** [comment] 2021-11-02 04:13
What about a fallback `imp` that just stubs everything out with errors for unsupported platforms? If any more platforms eventually get support, their `imp`s could just take precedence over the fallback (`cfg_if` might be helpful here 🤔)

**Comment by nagisa** [comment] 2021-11-02 22:31
I'm not currently targeting WASM platforms often enough to tell if that would be an appropriate approach. I know the standard library does it for wasm, but it is also a fairly controversial thing that Rust has done for that target in particular.

**Comment by Cyborus04** [comment] 2021-11-03 05:06
I guess it is counter to the (rather core) idea of failing to compile rather than failing to run

**Comment by jiyinyiyong** [comment] 2021-11-03 05:21
personally my main concern is the error messages, which were supposed to tell me what's the problem and what to do next, rather than leaving me at a loss only to Google for luck.

**Comment by Cyborus04** [comment] 2021-11-03 05:27
Maybe instead of a stub fallback, a `compile_error!` that states it isn't supported on the current platform?

**Comment by Cyborus04** [comment] 2021-11-03 12:22
Ah, I tried implementing this, but the compiler's output is now all the previous errors _alongside_ the new "unsupported platform" one, instead of just the unsupported one on its own as I intended. How about a stub fallback which is guarded by the `compiler_error!`?

**Comment by nagisa** [comment] 2021-11-13 22:18
Hm, I'm not sure a stub fallback is necessary after all. Instead you should be able to `#[cfg(any(unix, windows))]` all the common implementation stuff in `lib.rs` to get rid of the rest of the errors.

Sorry for the late response here.

**Comment by nagisa** [comment] 2021-11-14 14:24
Hey all, I made some changes in #98 which may help with this significantly. Could somebody try patching this in their failing projects and see if it helps in any way? You can do it by adding a following section to your `Cargo.toml` (untested, but should work):

```toml
[patch.crates-io]
libloading = { git = 'https://github.com/nagisa/rust_libloading', branch = 'nagisa/072' }
```

**Comment by jiyinyiyong** [comment] 2021-11-14 14:49
tried in my project, now I can use your fork of `libloading` without adding `[target.'cfg(not(target_arch = "wasm32"))'.dependencies]`. is that correct, just no longer throwing errors?

related lines of mine(but I modified at local disk),
https://github.com/calcit-lang/calcit_runner.rs/blob/main/Cargo.toml#L36-L37
https://github.com/calcit-lang/calcit-wasm-play/blob/main/Cargo.toml#L9-L10

**Comment by nagisa** [comment] 2021-11-14 14:51
Yes, the intended result is that `libloading` now compiles, but does not attempt to expose the `Library` and `Symbol` types, allowing users on the other platforms decide how they want to deal with this absence by themselves more easily.

**Comment by nagisa** [comment] 2021-11-15 21:06
libloading 0.7.2 onwards should build fine on wasm32-unknown-unknown.

**Closed by nagisa** 2021-11-15 21:06 UTC
Labels: enhancement, help wanted
