### ISSUE TITLE
dylib function that returns custom type when retrieved produces Segmentation Fault on macOS

### ISSUE THREAD

**Issue by fasihrana** [nagisa/rust_libloading#30] opened 2017-09-04 15:00 UTC
macOS Sierra: 10.12.6 (16G29)

This issue references the issue created for [rust-json](https://github.com/maciejhirsz/json-rust/issues/120)

Sample Code is as follows:

Code for the dynamic library function is as follows:

    #[macro_use]
    extern crate json;

    use json::JsonValue;
    
    #[no_mangle]
    pub fn methods() -> JsonValue
    {
    	let rt = array![
    		object!{
    			"fn" => "method 1"
        		}
    	];
    	rt
    }

Code for my main.rs file is as follows:

    extern crate json;
    extern crate libloading as lib;
    
    use std::env;
    use json::JsonValue;
    
    unsafe fn call_dynamic(libname: &String) -> lib::Result<()> {
    	let dylib = try!(lib::Library::new(libname));
    	let findmethods: lib::Symbol<fn() -> JsonValue> = dylib.get(b"methods")?;
    	let funcs = findmethods();
    	println!("{:#}", funcs);
    	Ok(())
    }
    
    fn main(){
    	let args: Vec<String> = env::args().collect();
    	unsafe {
    		call_dynamic(&args[1]).unwrap();
    	}
    }

**Comment by nagisa** [comment] 2017-09-04 21:11
This could be a duplicate of https://github.com/nagisa/rust_libloading/issues/5, although I do need a backtrace to make sure.

You should make sure that the functions you’re trying to load dynamically are using a well-known ABI such as the `C` one. The default does not provide any ABI guarantees. Using a non-fully-`repr(C)` structures is likely to run into the same problems here.

**Comment by fasihrana** [comment] 2017-09-06 06:06
I'm not sure how to generate a backtrace on macOS. Any steps you could link me to?

I had the same problem when I used a custom enum. Then I tried Serde Json with libloading and that works perfectly fine. So my immediate problem has "gone away", but would like to get to the bottom of the issue.

**Comment by nagisa** [comment] 2017-09-06 09:11
Run your program under lldb or gdb:

lldb program # or gdb program

Wait for the program to crash. Then type

backtrace

And paste the output here. Make sure to compile both your dynamic library
and loading program with debug info enabled (i.e. not --release or if rustc
is used directly with a -g flag)

**Comment by nagisa** [comment] 2020-04-05 13:28
Closing as there has been no activity.

**Closed by nagisa** 2020-04-05 13:28 UTC
