### ISSUE TITLE
Support for dlmopen

### ISSUE THREAD

**Issue by htfy96** [nagisa/rust_libloading#55] opened 2019-06-17 18:06 UTC
`dlmopen` allows users to specify a namespace for shared libraries. Maybe a new wrapper at `os::unix::Library::dlmopen` can be provided for this case.

**Comment by nagisa** [comment] 2019-06-17 18:26
Duplicate of https://github.com/nagisa/rust_libloading/issues/36.

I still have found no indication that any other unix targets other than GNU have this function available. It is not available for macOS for example.

**Closed by nagisa** 2019-06-17 18:26 UTC
