### ISSUE TITLE
`Deref` in `Symbol` can leak a raw function pointer.

### ISSUE THREAD

**Issue by lvella** [nagisa/rust_libloading#158] opened 2024-09-27 14:19 UTC
I can just take a `Symbol`, deref into a `&T`, clone the function pointer `T`, and boom, I am completely free from the `'lib` lifetime.

Considering function pointers always have `'static` lifetime, I don't think there is any safe alternative for this problem. Maybe manually implement `Fn` trait? But this is unstable.

**Comment by nagisa** [comment] 2024-09-27 22:17
Duplicate of https://github.com/nagisa/rust_libloading/issues/13

**Closed by nagisa** 2024-09-27 22:17 UTC
